package cli

import (
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/rebaze/rio/internal/receipt"
)

// latestOutput locates generated bytes through the newest execution receipt in
// this test's private output root. Production has no mutable "latest" file.
func latestOutput(t *testing.T, dir, out string) string {
	t.Helper()
	root := out
	if !filepath.IsAbs(root) {
		root = filepath.Join(dir, out)
	}
	entries, e := os.ReadDir(filepath.Join(root, "runs"))
	if e != nil && !os.IsNotExist(e) {
		t.Fatal(e)
	}
	var paths []string
	for _, entry := range entries {
		if entry.IsDir() {
			path := filepath.Join(root, "runs", entry.Name(), "record.json")
			if _, e := os.Stat(path); e == nil {
				paths = append(paths, path)
			}
		}
	}
	chosen := root
	var newest time.Time
	for _, path := range paths {
		raw, e := os.ReadFile(path)
		if e != nil {
			t.Fatal(e)
		}
		d, e := receipt.Parse(raw)
		if e != nil {
			t.Fatal(e)
		}
		if d.Run.Operation != "normalize" && d.Run.Operation != "pipeline" {
			continue
		}
		started, e := time.Parse(time.RFC3339Nano, d.Run.StartedAt)
		if e != nil {
			t.Fatal(e)
		}
		if started.After(newest) {
			newest = started
			chosen = filepath.Dir(path)
		}
	}
	return chosen
}
func requireNoNormalizedOutputs(t *testing.T, root string) {
	t.Helper()
	e := filepath.WalkDir(root, func(path string, d fs.DirEntry, e error) error {
		if os.IsNotExist(e) {
			return nil
		}
		if e != nil {
			return e
		}
		if d.IsDir() && d.Name() == ".internal" {
			return filepath.SkipDir
		}
		if d.IsDir() {
			return nil
		}
		if d.Name() == "index.json" || strings.HasSuffix(d.Name(), ".cdx.json") || strings.HasSuffix(d.Name(), ".intoto.json") {
			t.Errorf("failed input published generated output: %s", path)
		}
		if d.Name() == "record.json" {
			raw, e := os.ReadFile(path)
			if e != nil {
				return e
			}
			r, e := receipt.Parse(raw)
			if e != nil {
				return e
			}
			if r.Run.Outcome != "failed" {
				t.Errorf("failed invocation receipt claims %s", r.Run.Outcome)
			}
		}
		return nil
	})
	if e != nil {
		t.Fatal(e)
	}
}

func requireProgressAndReceipt(t *testing.T, r run, progress string) {
	t.Helper()
	if !strings.HasPrefix(r.stdout, progress) {
		t.Fatalf("stdout=%q want progress prefix %q", r.stdout, progress)
	}
	lines := strings.Split(strings.TrimSpace(strings.TrimPrefix(r.stdout, progress)), "\n")
	if len(lines) != 2 || !strings.HasPrefix(lines[0], "run run-") || !strings.HasPrefix(lines[1], "receipt: ") {
		t.Fatalf("missing discoverable run/receipt: %q", r.stdout)
	}
	path := strings.TrimPrefix(lines[1], "receipt: ")
	raw, e := os.ReadFile(path)
	if e != nil {
		t.Fatal(e)
	}
	d, e := receipt.Parse(raw)
	if e != nil {
		t.Fatal(e)
	}
	if !strings.Contains(lines[0], d.Run.ID) {
		t.Fatal("printed run disagrees with receipt")
	}
}
